#!/usr/bin/env python

import grizz
import sys

def main():
    def post_render():
        """post-render command: copy contents of in/ to out/"""
        import os
        os.system("cp -R in/ out")

    PREVIEW_CMD = "preview"
    RENDER_CMD = "render"
    cmds = {"preview": PREVIEW_CMD, "render": RENDER_CMD, "test": PREVIEW_CMD}
    if len(sys.argv) < 2 or sys.argv[1] not in cmds:
        print 'USAGE: %s (%s|%s)' % (sys.argv[0], RENDER_CMD, PREVIEW_CMD)
        sys.exit(1)
    cmd = cmds[sys.argv[1]]
    if cmd == RENDER_CMD or cmd == PREVIEW_CMD:
        grizz.render_from_manifest('./manifest')
        post_render()
    if cmd == PREVIEW_CMD:
        grizz.serve('./out/')

if __name__ == '__main__':
    main()
